### PR TITLE
Update ICSE 2025

### PR DESCRIPTION
**Pull request by ztw33**
### Which conference does this PR update?

- ICSE 2025

### Related URL

- https://conf.researchr.org/home/icse-2025

### CODE REVIEW

**Review by jacklightChen — COMMENTED** [review]
The `deadline` field is required for each item, and each item can only contain one comment, please check the format~

**Comment by ztw33** [comment]
> The `deadline` field is required for each item, and each item can only contain one comment, please check the format~

ICSE2025 has two cycles. For each cycle, I added `abstract_deadline` and `deadline`, and added a comment for each (abstract_)deadline. Do you mean I can only add one comment per conference, not per deadline? Cuz I see every submission deadline used to have a comment added to it. Thank you!

**Comment by ztw33** [comment]
Sorry, just checked again and found I missed `id`. 😥

**Comment by jacklightChen** [comment]
Oops, I didn't notice the missed `id` either, but now everything looks fine. Let's proceed with the merge, thank your for the update~

**Review by jacklightChen — APPROVED** [review]

**Pull request merged**
