### PR TITLE
Update SANER 2024

### PR DESCRIPTION
**Pull request by iCSawyer**
### Which conference does this PR update?
- saner 2024

### Related URL
- https://conf.researchr.org/home/saner-2024

### CODE REVIEW

**Comment by ViGeng** [comment]
Please keep the previous ones and add a new entry for the new one, e.g., [AAAI.yaml](https://github.com/ccfddl/ccf-deadlines/blob/main/conference/AI/aaai.yml)

**Comment by iCSawyer** [comment]
update~

**Comment by jacklightChen** [comment]
We now recommend using `abstract_deadline` for abstract deadlines to prevent confusion in the WeChat applet. I have adjusted the format. @ViGeng plz take a review and try an approval ~

**Comment by ViGeng** [comment]
> We now recommend using `abstract_deadline` for abstract deadlines to prevent confusion in the WeChat applet. I have adjusted the format. @ViGeng plz take a review and try an approval (may change the visibility first)~

Sure. Visibility changed.

**Review by ViGeng — APPROVED** [review]
Generally, data entries with `string` type should be quoted by `''` when there are any blanks or special characters. (eg. `dates` in the yaml file)
I have checked other confs with similar situations, but they work well.😂 So I approve this change.

**Comment by ViGeng** [comment]
> We now recommend using `abstract_deadline` for abstract deadlines to prevent confusion in the WeChat applet. I have adjusted the format. @ViGeng plz take a review and try an approval (may change the visibility first)~

it seems still not working.

**Comment by jacklightChen** [comment]
> > We now recommend using `abstract_deadline` for abstract deadlines to prevent confusion in the WeChat applet. I have adjusted the format. @ViGeng plz take a review and try an approval (may change the visibility first)~
> 
> it seems still not working.

Well, that is frustrating. Let's find out the reason later.

**Review by jacklightChen — APPROVED** [review]

**Pull request merged**
