### PR TITLE
[Update] readme git workflow best practice

### PR DESCRIPTION
**Pull request by ViGeng**
add a git workflow recommendation.

### CODE REVIEW

**Review by fffmath — APPROVED** [review]

**Comment by ViGeng** [comment]
It seems the bot is not working... 😂

**Comment by jacklightChen** [comment]
> It seems the bot is not working... 😂

seems weird, trying to find the reason

**Comment by jacklightChen** [comment]
@Mergifyio refresh

**Comment by jacklightChen** [comment]
image
Mergify check failed, emmm

**Comment by jacklightChen** [comment]
@ViGeng BTW, please add the same recommendation to README.zh-CN. :)

**Comment by ViGeng** [comment]
Chinese README version has been updated by [commit](https://github.com/ccfddl/ccf-deadlines/pull/316/commits/cd67f55f580143b10ed5fa6775cd01fece400173)

**Review by jacklightChen — APPROVED** [review]

**Pull request merged**
